spring:
  application:
    name: backend

  config:
    import:
      - "optional:aws-parameterstore:${PARAMETER_STORE_PATH}"

  datasource:
    driver-class-name: org.h2.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

jwt:
  access:
    secret: ${jwt.access.secret}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace