name: cd-develop

on:
  workflow_dispatch:
#  pull_request:
#    types: [closed]
#    branches: [develop]

jobs:
  build-image:
#    if: github.event.pull_request.merged == true
    environment: develop
    runs-on: ubuntu-latest

    outputs:
      IMAGE_TAG: ${{ steps.image-tag-id.outputs.IMAGE_TAG }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: git clone repository
        uses: actions/checkout@v4

      - name: setup image tag
        id: image-tag-id
        run: echo IMAGE_TAG=${GITHUB_SHA::${{ vars.SHA_SHORT_LENGTH }}} >> $GITHUB_OUTPUT

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: login to aws ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: docker build & push
        working-directory: ${{ vars.WORKING_DIRECTORY }}
        run: |
          chmod +x gradlew
          ./gradlew clean build
          docker build -f Dockerfile -t ${{ secrets.REGISTRY }}/${{ secrets.REPOSITORY }}:${{ steps.image-tag-id.outputs.IMAGE_TAG }} .
          docker push ${{ secrets.REGISTRY }}/${{ secrets.REPOSITORY }}:${{ steps.image-tag-id.outputs.IMAGE_TAG }}

  deploy:
    needs: [build-image]
    environment: develop
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: setup deploy time
        run: echo DEPLOY_TIME=$(date +'%Y%m%d%H%M%S') >> $GITHUB_ENV

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: deploy to ec2 via aws ssm
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "docker pull ${{ secrets.REGISTRY }}/${{ secrets.REPOSITORY }}:${{ needs.build-image.outputs.IMAGE_TAG }}"
            ]' \
            --region ${{ vars.AWS_REGION }}
